include(CheckCXXSourceCompiles)

set(TORCS_BRIDGE_RETAINED_CORE_AVAILABLE OFF)
set(TORCS_BRIDGE_RETAINED_CORE_LINKABLE OFF)
set(TORCS_BRIDGE_RETAINED_CORE_MISSING "")
set(TORCS_BRIDGE_PLIB_HINTS "")
set(TORCS_BRIDGE_PLIB_LIBRARY_HINTS "")

list(APPEND TORCS_BRIDGE_PLIB_HINTS
	"${TORCS_BRIDGE_TORCS_ROOT}/.cache/plib-1.8.5/include"
)

list(APPEND TORCS_BRIDGE_PLIB_LIBRARY_HINTS
	"${TORCS_BRIDGE_TORCS_ROOT}/.cache/plib-1.8.5/lib"
)

if(WIN32)
	list(APPEND TORCS_BRIDGE_PLIB_HINTS
		"${TORCS_BRIDGE_TORCS_ROOT}/src/windows/include"
	)

	if(CMAKE_SIZEOF_VOID_P EQUAL 8)
		list(APPEND TORCS_BRIDGE_PLIB_LIBRARY_HINTS
			"${TORCS_BRIDGE_TORCS_ROOT}/src/windows/lib64"
		)
	else()
		list(APPEND TORCS_BRIDGE_PLIB_LIBRARY_HINTS
			"${TORCS_BRIDGE_TORCS_ROOT}/src/windows/lib"
		)
	endif()
endif()

find_path(TORCS_BRIDGE_PLIB_INCLUDE_DIR
	NAMES plib/sg.h sg.h
	HINTS ${TORCS_BRIDGE_PLIB_HINTS}
	DOC "Directory containing PLIB sg/ul headers."
)

find_library(TORCS_BRIDGE_PLIB_SG_LIBRARY
	NAMES plibsg sg
	HINTS ${TORCS_BRIDGE_PLIB_LIBRARY_HINTS}
	DOC "PLIB sg library."
)

find_library(TORCS_BRIDGE_PLIB_UL_LIBRARY
	NAMES plibul ul
	HINTS ${TORCS_BRIDGE_PLIB_LIBRARY_HINTS}
	DOC "PLIB ul library."
)

if(NOT TORCS_BRIDGE_PLIB_INCLUDE_DIR)
	list(APPEND TORCS_BRIDGE_RETAINED_CORE_MISSING "PLIB headers")
endif()

if(NOT TORCS_BRIDGE_PLIB_SG_LIBRARY)
	list(APPEND TORCS_BRIDGE_RETAINED_CORE_MISSING "PLIB sg library")
endif()

if(NOT TORCS_BRIDGE_PLIB_UL_LIBRARY)
	list(APPEND TORCS_BRIDGE_RETAINED_CORE_MISSING "PLIB ul library")
endif()

if(TORCS_BRIDGE_RETAINED_CORE_MISSING)
	string(REPLACE ";" ", " TORCS_BRIDGE_RETAINED_CORE_MISSING_TEXT "${TORCS_BRIDGE_RETAINED_CORE_MISSING}")
	message(STATUS "Retained TORCS core preflight: missing ${TORCS_BRIDGE_RETAINED_CORE_MISSING_TEXT}; retained-core targets disabled.")
else()
	set(TORCS_BRIDGE_RETAINED_CORE_AVAILABLE ON)

	set(TORCS_BRIDGE_SAVED_REQUIRED_INCLUDES "${CMAKE_REQUIRED_INCLUDES}")
	set(TORCS_BRIDGE_SAVED_REQUIRED_LIBRARIES "${CMAKE_REQUIRED_LIBRARIES}")
	set(CMAKE_REQUIRED_INCLUDES "${TORCS_BRIDGE_PLIB_INCLUDE_DIR}")
	set(CMAKE_REQUIRED_LIBRARIES
		"${TORCS_BRIDGE_PLIB_SG_LIBRARY};${TORCS_BRIDGE_PLIB_UL_LIBRARY}"
	)
	unset(TORCS_BRIDGE_PLIB_SG_LINKS CACHE)
	check_cxx_source_compiles("
		#include <plib/sg.h>
		int main()
		{
			sgMat4 matrix;
			sgMakeCoordMat4(matrix, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f);
			return 0;
		}
	" TORCS_BRIDGE_PLIB_SG_LINKS)
	set(CMAKE_REQUIRED_INCLUDES "${TORCS_BRIDGE_SAVED_REQUIRED_INCLUDES}")
	set(CMAKE_REQUIRED_LIBRARIES "${TORCS_BRIDGE_SAVED_REQUIRED_LIBRARIES}")

	if(TORCS_BRIDGE_PLIB_SG_LINKS)
		set(TORCS_BRIDGE_RETAINED_CORE_LINKABLE ON)
		message(STATUS "Retained TORCS core preflight: PLIB dependencies found and linkable.")
	else()
		message(STATUS "Retained TORCS core preflight: PLIB files found, but sg symbols do not link; retained smoke target disabled.")
	endif()
endif()

if(TORCS_BRIDGE_ENABLE_RETAINED_CORE AND NOT TORCS_BRIDGE_RETAINED_CORE_AVAILABLE)
	message(FATAL_ERROR
		"TORCS_BRIDGE_ENABLE_RETAINED_CORE is ON, but retained-core dependencies are missing: "
		"${TORCS_BRIDGE_RETAINED_CORE_MISSING_TEXT}. "
		"Install PLIB or provide TORCS_BRIDGE_PLIB_INCLUDE_DIR, "
		"TORCS_BRIDGE_PLIB_SG_LIBRARY, and TORCS_BRIDGE_PLIB_UL_LIBRARY."
	)
endif()
