set(TORCS_BRIDGE_RETAINED_CORE_AVAILABLE OFF)
set(TORCS_BRIDGE_RETAINED_CORE_MISSING "")

find_path(TORCS_BRIDGE_PLIB_INCLUDE_DIR
	NAMES plib/sg.h sg.h
	DOC "Directory containing PLIB sg/ul headers."
)

find_library(TORCS_BRIDGE_PLIB_SG_LIBRARY
	NAMES plibsg sg
	DOC "PLIB sg library."
)

find_library(TORCS_BRIDGE_PLIB_UL_LIBRARY
	NAMES plibul ul
	DOC "PLIB ul library."
)

if(NOT TORCS_BRIDGE_PLIB_INCLUDE_DIR)
	list(APPEND TORCS_BRIDGE_RETAINED_CORE_MISSING "PLIB headers")
endif()

if(NOT TORCS_BRIDGE_PLIB_SG_LIBRARY)
	list(APPEND TORCS_BRIDGE_RETAINED_CORE_MISSING "PLIB sg library")
endif()

if(NOT TORCS_BRIDGE_PLIB_UL_LIBRARY)
	list(APPEND TORCS_BRIDGE_RETAINED_CORE_MISSING "PLIB ul library")
endif()

if(TORCS_BRIDGE_RETAINED_CORE_MISSING)
	string(REPLACE ";" ", " TORCS_BRIDGE_RETAINED_CORE_MISSING_TEXT "${TORCS_BRIDGE_RETAINED_CORE_MISSING}")
	message(STATUS "Retained TORCS core preflight: missing ${TORCS_BRIDGE_RETAINED_CORE_MISSING_TEXT}; retained-core targets disabled.")
else()
	set(TORCS_BRIDGE_RETAINED_CORE_AVAILABLE ON)
	message(STATUS "Retained TORCS core preflight: PLIB dependencies found.")
endif()

if(TORCS_BRIDGE_ENABLE_RETAINED_CORE AND NOT TORCS_BRIDGE_RETAINED_CORE_AVAILABLE)
	message(FATAL_ERROR
		"TORCS_BRIDGE_ENABLE_RETAINED_CORE is ON, but retained-core dependencies are missing: "
		"${TORCS_BRIDGE_RETAINED_CORE_MISSING_TEXT}. "
		"Install PLIB or provide TORCS_BRIDGE_PLIB_INCLUDE_DIR, "
		"TORCS_BRIDGE_PLIB_SG_LIBRARY, and TORCS_BRIDGE_PLIB_UL_LIBRARY."
	)
endif()
